/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./landing/**/*.{js,ts,jsx,tsx}",
    "./auth/**/*.{js,ts,jsx,tsx}",
    "./onboarding/**/*.{js,ts,jsx,tsx}",
    "./dashboard/**/*.{js,ts,jsx,tsx}",
    "./courses/**/*.{js,ts,jsx,tsx}",
    "./community/**/*.{js,ts,jsx,tsx}",
    "./events/**/*.{js,ts,jsx,tsx}",
    "./developer-hub/**/*.{js,ts,jsx,tsx}",
    "./ai-tutor/**/*.{js,ts,jsx,tsx}",
    "./profile/**/*.{js,ts,jsx,tsx}",
    "./admin/**/*.{js,ts,jsx,tsx}",
    "./learning-paths/**/*.{js,ts,jsx,tsx}",
    "./App.jsx",
    "./routes.jsx"
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          deep: '#f5f7fa',
          card: 'rgba(255, 255, 255, 0.9)',
          border: 'rgba(0, 0, 0, 0.08)',
          neonOrange: '#ff6b00',
          neonCyan: '#00f0ff',
          neonPurple: '#ad00ff',
        },
        "tertiary-fixed-dim": "#64748b",
        "on-primary-fixed-variant": "#1e40af",
        "on-primary-container": "#1e293b",
        "tertiary": "#64748b",
        "info-blue": "#2563EB",
        "primary-fixed-dim": "#1d4ed8",
        "primary": "#2563EB",
        "on-tertiary": "#f8fafc",
        "success-emerald": "#10b981",
        "vibrant-orange": "#FF6B00",
        "surface-tint": "#2563EB",
        "on-tertiary-container": "#1e293b",
        "on-surface-variant": "#475569",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#f1f5f9",
        "surface-variant": "#f1f5f9",
        "inverse-surface": "#0f172a",
        "error": "#ef4444",
        "on-primary": "#ffffff",
        "surface-stroke": "rgba(0, 0, 0, 0.08)",
        "on-error": "#ffffff",
        "glass-white": "rgba(255, 255, 255, 0.85)",
        "secondary-fixed-dim": "#94a3b8",
        "deep-charcoal": "#1a1f2e",
        "tertiary-fixed": "#e2e8f0",
        "surface-container-high": "#e2e8f0",
        "on-secondary-fixed-variant": "#475569",
        "on-secondary": "#1e293b",
        "surface-container-low": "#f8fafc",
        "background": "#f5f7fa",
        "primary-container": "#dbeafe",
        "on-error-container": "#991b1b",
        "outline": "#cbd5e1",
        "surface-bright": "#ffffff",
        "surface-container-highest": "#cbd5e1",
        "on-tertiary-fixed": "#1e293b",
        "surface-container": "#f1f5f9",
        "on-background": "#1a1f2e",
        "outline-variant": "#e2e8f0",
        "surface-dim": "#e8ecf0",
        "on-secondary-fixed": "#1e293b",
        "secondary": "#64748b",
        "primary-fixed": "#dbeafe",
        "inverse-on-surface": "#f8fafc",
        "secondary-fixed": "#f1f5f9",
        "tertiary-container": "#f1f5f9",
        "on-primary-fixed": "#1e40af",
        "on-tertiary-fixed-variant": "#475569",
        "inverse-primary": "#3b82f6",
        "on-secondary-container": "#334155",
        "on-surface": "#1a1f2e",
        "surface": "#f5f7fa",
        "error-container": "#fee2e2"
      },
      fontFamily: {
        sans: ['Outfit', 'Inter', 'sans-serif'],
      },
      boxShadow: {
        'glow-orange': '0 0 20px rgba(255, 107, 0, 0.15)',
        'glow-cyan': '0 0 20px rgba(0, 240, 255, 0.15)',
        'glow-purple': '0 0 20px rgba(173, 0, 255, 0.15)',
      }
    },
  },
  plugins: [],
}
