/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./landing/**/*.{js,ts,jsx,tsx}",
    "./auth/**/*.{js,ts,jsx,tsx}",
    "./onboarding/**/*.{js,ts,jsx,tsx}",
    "./dashboard/**/*.{js,ts,jsx,tsx}",
    "./courses/**/*.{js,ts,jsx,tsx}",
    "./community/**/*.{js,ts,jsx,tsx}",
    "./events/**/*.{js,ts,jsx,tsx}",
    "./developer-hub/**/*.{js,ts,jsx,tsx}",
    "./ai-tutor/**/*.{js,ts,jsx,tsx}",
    "./profile/**/*.{js,ts,jsx,tsx}",
    "./admin/**/*.{js,ts,jsx,tsx}",
    "./App.jsx",
    "./routes.jsx"
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          deep: '#060814',
          card: 'rgba(15, 23, 42, 0.4)',
          border: 'rgba(255, 255, 255, 0.08)',
          neonOrange: '#ff6b00',
          neonCyan: '#00f0ff',
          neonPurple: '#ad00ff',
        },
        "tertiary-fixed-dim": "#c1c8ca",
        "on-primary-fixed-variant": "#7a3000",
        "on-primary-container": "#572000",
        "tertiary": "#586062",
        "info-blue": "#0984E3",
        "primary-fixed-dim": "#ffb693",
        "primary": "#a04100",
        "on-tertiary": "#ffffff",
        "success-emerald": "#00B894",
        "vibrant-orange": "#FF6B00",
        "surface-tint": "#a04100",
        "on-tertiary-container": "#2b3234",
        "on-surface-variant": "#5a4136",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e1e3e4",
        "surface-variant": "#f8ddd2",
        "inverse-surface": "#3d2d26",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-stroke": "rgba(0, 0, 0, 0.08)",
        "on-error": "#ffffff",
        "glass-white": "rgba(255, 255, 255, 0.7)",
        "secondary-fixed-dim": "#c5c7c8",
        "deep-charcoal": "#1A1A1B",
        "tertiary-fixed": "#dde4e6",
        "surface-container-high": "#fee3d8",
        "on-secondary-fixed-variant": "#454748",
        "on-secondary": "#ffffff",
        "surface-container-low": "#fff1eb",
        "background": "#fff8f6",
        "primary-container": "#ff6b00",
        "on-error-container": "#93000a",
        "outline": "#8e7164",
        "surface-bright": "#fff8f6",
        "surface-container-highest": "#f8ddd2",
        "on-tertiary-fixed": "#161d1f",
        "surface-container": "#ffeae1",
        "on-background": "#261812",
        "outline-variant": "#e2bfb0",
        "surface-dim": "#efd5ca",
        "on-secondary-fixed": "#191c1d",
        "secondary": "#5c5f60",
        "primary-fixed": "#ffdbcc",
        "inverse-on-surface": "#ffede6",
        "secondary-fixed": "#e1e3e4",
        "tertiary-container": "#939a9c",
        "on-primary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#41484a",
        "inverse-primary": "#ffb693",
        "on-secondary-container": "#626566",
        "on-surface": "#261812",
        "surface": "#fff8f6",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        sans: ['Outfit', 'Inter', 'sans-serif'],
      },
      boxShadow: {
        'glow-orange': '0 0 20px rgba(255, 107, 0, 0.15)',
        'glow-cyan': '0 0 20px rgba(0, 240, 255, 0.15)',
        'glow-purple': '0 0 20px rgba(173, 0, 255, 0.15)',
      }
    },
  },
  plugins: [],
}
